#
all:
	javac -cp lib/ src/POOCasino.java src/Player_B02902096.java src/Shuffler.java -d lib/
run:
	java -cp lib/ POOCasino 2000 20000 Player_B02902096 PlayerB02902069 Player_B02902096 PlayerB02902069
