#
all:Playgame.java Player.java Card.java CardComparator.java Comparator.java 
	javac Playgame.java Player.java Card.java CardComparator.java Comparator.java 
clean:
	rm -f Playgame.class
	rm -f Player.class
	rm -f Card.class
	rm -f CardComparator.class
	rm -f Comparator.class