#
all:
	javac POOCasino.java Player.java Card.java Judge.java Shuffler.java Computer.java

clean:
	rm -f POOCasino.class 
	rm -f Player.class
	rm -f Card.class
	rm -f Judge.class
	rm -f Computer.class
	rm -f Shuffler.class
	rm -f CardComparator.class
	rm -f RandomIndex.class
run:
	java POOCasino