#
all:
	javac PlayGame.java Player.java Card.java CardComparator.java Oldmaid.java
	java PlayGame
clean:
	rm -f PlayGame.class 
	rm -f Player.class
	rm -f Card.class
	rm -f CardComparator.class
	rm -f Tradition_Version.class
	rm -f One_Ghost_Version.class
	rm -f Two_Ghost_Version.class
	rm -f Oldmaid.class